[package]
name = "filelocksmith"
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["Caelan Sayler <git@caesay.com>"]
description = "Detect what processes are locking a file or folder on Windows"
readme = "README.md"
homepage = "https://github.com/velopack/filelocksmith-rs"
repository = "https://github.com/velopack/filelocksmith-rs"
documentation = "https://docs.rs/filelocksmith"
keywords = ["windows", "locksmith", "powertoys", "find", "locking"]
categories = ["development-tools"]

exclude = [
    "PowerToys/*",
    "!PowerToys/src/modules/FileLocksmith/FileLocksmithLibInterop/**/*"
]

[features]
private-docs-rs = []

[package.metadata.docs.rs]
features = ["private-docs-rs"] # workaround to skip C++ build on docs.rs

[lib]
name = "filelocksmith"
path = "src/lib.rs"

[build-dependencies]
cc = "1.1"